# Generated by Django 6.0.2 on 2026-02-12 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grades", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="valeur",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ]
            ),
        ),
    ]
