# Generated by Django 6.0.2 on 2026-02-09 11:11

import courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier_pdf', models.FileField(upload_to=courses.models.upload_to)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='teachers.teacher')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='formations.formation')),
            ],
        ),
    ]
