# Generated by Django 6.0.2 on 2026-02-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('enseignants', models.ManyToManyField(blank=True, related_name='formations', to='teachers.teacher')),
            ],
        ),
    ]
